Parameters:
  thisBucketName:
    Type: String
    Default: day0-kp-2022

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref thisBucketName