image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

stages:
    - build

build:
    stage: build
    before_script:
        - uname -a
        - apt-get update
        - apt-get install -y make
        # - apt install -y build-essential
    script:
        - make deploy
    # artifacts:
    #     paths:
    #         - build/
