stages:
    - build
    # - test

build:
    stage: build
    script:
        - echo "Building"
        # - mkdir build
        - make deploy
    artifacts:
        paths:
            - build/

# test:
#     stage: test
#     script:
#         - echo "Testing"
#         - test -f "build/info.txt"