image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

stages:
    - infra_build
    - test


infra_build:
    stage: infra_build
    before_script:
        - uname -a
        - apt-get update
        - apt-get install -y make
        # - apt install -y build-essential
    script:
        - make deploy
    # artifacts:
    #     paths:
    #         - build/

test:
    stage: test
    script:
