# image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
image: ubuntu:latest

stages:
    - build


build:
    stage: build
    before_script:
        - uname -a
        - pwd
        - apt-get update
        - apt-get install -y make
        - apt install -y build-essential
    script:
        - make deploy
    artifacts:
        paths:
            - build/
