image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

stages:
    - build


build:
    stage: build
    before_script:
        - uname -a
        - pwd
        - sudo apt-get update
        - sudo apt-get install -y make
        - sudo apt install -y build-essential
    script:
        - make deploy
    artifacts:
        paths:
            - build/
