Resources:
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/compute/ec2.yaml
      Parameters:
        SubnetID: !ImportValue PublicSubnet2ID
