Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/network/vpc.yaml

  Security:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/network/security.yaml
      Parameters:
        VPCId: !GetAtt VPC.Outputs.StackVPCId

  Gateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/network/gateway.yaml
      Parameters:
        VPCId: !GetAtt VPC.Outputs.StackVPCId

  Subnet:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/network/subnet.yaml
      Parameters:
        VPCId: !GetAtt VPC.Outputs.StackVPCId

  Route: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/network/route.yaml
      Parameters:
        VPCId: !GetAtt VPC.Outputs.StackVPCId
        IGWId: !GetAtt Gateway.Outputs.StackIGWId
        PublicSubnet1Id: !GetAtt Subnet.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt Subnet.Outputs.PublicSubnet2Id
        PrivateSubnet1Id: !GetAtt Subnet.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt Subnet.Outputs.PrivateSubnet2Id

  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/iam/role.yaml

  s3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/storage/s3.yaml

  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/compute/ec2.yaml
      Parameters:
        SubnetID: !GetAtt Subnet.Outputs.PublicSubnet1Id
        SecurityGroupID: !GetAtt Security.Outputs.StackSecurityGroupId
        ec2IAMInstanceProfileName: !GetAtt IAM.Outputs.ec2IAMInstanceProfileName
        S3BucketName: !GetAtt s3.Outputs.StackS3BucketName

  cloudwatch:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://day0-kp.s3.ap-southeast-1.amazonaws.com/cloudwatch/loggroup.yaml
