Parameters:
  VPCId:
    Type: String

  IGWId:
    Type: String
  
  PublicSubnet1Id:
    Type: String

  PublicSubnet2Id:
    Type: String

  PrivateSubnet1Id:
    Type: String

  PrivateSubnet2Id:
    Type: String


Resources:
  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCId

  myRoute:
    Type: AWS::EC2::Route
    # DependsOn: GatewayToInternet
    Properties:
      RouteTableId: !Ref myRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGWId

  myPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1Id
      RouteTableId: !Ref myRouteTable      

  myPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2Id
      RouteTableId: !Ref myRouteTable            